### ISSUE TITLE
No way out of modal?

### ISSUE THREAD

**Issue by kghbln** [oetterer/BootstrapComponents#8]
**Setup**
- MediaWiki | 1.30.0 (d0c8f49)19:49, 5 January 2018
- PHP | 7.0.27-0+deb9u1 (apache2handler)
- MariaDB | 10.1.26-MariaDB-0+deb9u1
- Chameleon | 1.6.1-alpha (e4e46b7) 09:34, 8 January 2018
- Bootstrap | 1.2.3 (cdb1d58) 23:23, 30 November 2017
- BootstrapComponents | 1.1.1 (4ca0de9) 14:21, 2 February 2018

- Firefox 58.0.1
- Linux Mint 18.3

**Issue**
Once I clicked on [modal](https://sandbox.semantic-mediawiki.org/wiki/BootstrapComponents/Modal) there does not seem to be a way out except for reloading the page.

![bildschirmfoto vom 2018-02-07 10-16-26](https://user-images.githubusercontent.com/1104078/35908351-b103c54a-0bf0-11e8-9ea4-a961c56bf57c.png)

**Comment by oetterer** [comment]
hmm. there is a css file to rectify this which apparently does not get loaded. will have a look. Thank you for testing and reporting!

**Comment by oetterer** [comment]
@kghbln 
Well, it looks like a problem the modal has with the vector skin. Therefore the extension loads an additional css to remove the modal-backdrop when vector is in use. With chameleon however, it _should_ work, therefore the css is not loaded.

I tried to replicate the issue with
* mw 1.30
* php 5.6
* Chameleon 1.6.1-alpha
* Bootstrap 1.2.3 (cdb1d58) 23:23, 30 November 2017
* BootstrapComponents | 1.1.1 (4ca0de9) 14:21, 2 February 2018

I'm assuming, you base the skin on the sandbox on chameleon's _fixedhead_ layout.

Here is, what it looks like for me:

![2018-02-07 17_59_18-bootstrapcomponents_modal](https://user-images.githubusercontent.com/9444462/35929983-064f937c-0c31-11e8-94ac-77109f024b54.png)

I disected the problem on the sandbox. Here is what my Firefox gave me:
* fixed header has z-index 1030
* modal-backdrop has z-index 1040
* modal has z-index 1050

so they sould stack neatly. Currently, I'm out of ideas. As a workaround you could add

```css
.modal-backdrop {
  display: none;
}
```
to the MediaWiki:Common.css. 

For the long term, I'm thinking of adding an additional configuration option to disable the modal-backdrop. Short term, I will look a little bit more into this issue, unfortunately my css is at a base level. :/

cheers

**Comment by kghbln** [comment]
Indeed Chameleon is using "fixedhead". The extra CSS did the job and the main issue reported here is fixed. :)

![bildschirmfoto vom 2018-02-07 18-51-58](https://user-images.githubusercontent.com/1104078/35932555-36621894-0c38-11e8-9bcd-b944af6c87c4.png)

Indeed the marked issue is still there and the z-index should fix it, but it somehow does not. Hmm ...

**Comment by kghbln** [comment]
@oetterer You were already admin, so you could have fiddled with the CSS yourself. :)

**Comment by oetterer** [comment]
Strange. same issues I had with my vector tests. I added

```css
.modal {
	top: 60px;
}
```
to Common.css on sandbox. Checked with current Firefox and chrome. Works for me now.

PS: @kghbln: I somehow forgot, that I had admin rights. But at least, the solution is properly documented here. :)

**Comment by kghbln** [comment]
Indeed. Thanks a lot for your help. Just [documented the solution](https://sandbox.semantic-mediawiki.org/w/index.php?title=BootstrapComponents%2FModal&action=historysubmit&type=revision&diff=8551&oldid=8522)

**Comment by oetterer** [comment]
@kghbln you are the best, thank you!
